name: Build and Deploy Node.js App to Azure Web App - CampusERP

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0" # Updated to meet Prisma's requirement
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Prepare Deployment Package
        run: |
          mkdir deploy
          cp -r dist deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp web.config deploy/
          cp -r prisma deploy/
          cd deploy
          npm install --only=production
          cd ..
          zip -r release.zip deploy/*

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
