name: Build and Deploy Node.js App to Azure Web App - CampusERP

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Step 3: Install dependencies and build
      - name: Install Dependencies and Build
        run: |
          rm -rf node_modules
          npm install
          npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 4: Generate Prisma Client
      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 5: Prepare deployment package
      - name: Create Deployment Package
        run: |
          cp -r node_modules dist/
          cp package*.json dist/
          cp web.config dist/
          cp -r prisma dist/
          cd dist
          zip -r ../deploy.zip .

      # Step 6: Upload artifact for deployment
      - name: Upload Artifact for Deployment Job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"

    steps:
      # Step 1: Download artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # Step 2: Azure CLI login
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "CampusERP"
          slot-name: "production"
          package: deploy.zip
