name: Build and Deploy Node.js App to Azure Web App - CampusERP

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Prepare Deployment Package
        run: |
          mkdir deploy
          xcopy dist deploy\dist /E/H/C/I
          xcopy prisma deploy\prisma /E/H/C/I
          xcopy node_modules deploy\node_modules /E/H/C/I
          copy package.json deploy\
          copy web.config deploy\
          copy iisnode.yml deploy\
          copy startup.js deploy\
        shell: cmd

      - name: Compress Deployment Package
        run: |
          Compress-Archive -Path deploy\* -DestinationPath release.zip
        shell: powershell

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "campusERP"
          package: release.zip
